USE EMPLOYEE_DB;

#Create a CTE that calculates the average employee salary and return employees earning above it.
WITH AVG_EMPLOYEE_SALARY AS (
    SELECT AVG(SALARY) as AVG_SALARY FROM EMPLOYEES)
SELECT e.* 
FROM EMPLOYEES e
JOIN AVG_EMPLOYEE_SALARY A 
ON e.SALARY>A.AVG_SALARY;

#Create a CTE that calculates employee count and average salary per department.
WITH AVG_SALARY_PER_DEPARTMENT AS(
    SELECT DEPARTMENT_ID, 
    COUNT(*) AS EMPLOYEE_COUNT,
    AVG(SALARY) AS AVG_SALARY
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
    )

SELECT * FROM AVG_SALARY_PER_DEPARTMENT;

#using window function
WITH DEPT_STATS AS (
    SELECT DEPARTMENT_ID,
    COUNT(*) OVER(PARTITION BY DEPARTMENT_ID) AS EMP_COUNT,
    AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID) AS AVG_SALARY
    FROM EMPLOYEES)
SELECT DISTINCT * FROM DEPT_STATS;

#Use a CTE to return the top 3 employees by salary.
WITH TOP_3_EMPLOYEES AS (
      SELECT * FROM EMPLOYEES ORDER BY SALARY DESC)
SELECT * FROM TOP_3_EMPLOYEES LIMIT 3;

#Use a CTE to calculate total revenue per customer.
USE ECOMMERCE_DB;
WITH TOTAL_REVENUE_PER_CUSTOMER AS(
     SELECT O.CUSTOMER_ID,
     SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE_PER_CUSTOMER
     FROM ORDERS O
     JOIN ORDER_ITEMS OI
     ON O.ORDER_ID=OI.ORDER_ID
     group by O.CUSTOMER_ID)

SELECT * FROM TOTAL_REVENUE_PER_CUSTOMER;

#Use a CTE to find the highest-revenue customer.
WITH TOTAL_REVENUE_PER_CUSTOMER AS(
     SELECT O.CUSTOMER_ID,
     SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
     FROM ORDERS O
     JOIN ORDER_ITEMS OI
     ON O.ORDER_ID=OI.ORDER_ID
     group by O.CUSTOMER_ID
     ORDER BY TOTAL_REVENUE DESC)

SELECT * FROM TOTAL_REVENUE_PER_CUSTOMER LIMIT 1;
