USE EMPLOYEE_DB;

#Display employees with their department names using INNER JOIN.
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME,EMP.LAST_NAME,DEPT.DEPARTMENT_NAME
FROM EMPLOYEES EMP 
INNER JOIN DEPARTMENTS DEPT
ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID;

#Display employees with their department names and locations
SELECT EMP.EMPLOYEE_ID,EMP.FIRST_NAME,EMP.LAST_NAME,DEPT.DEPARTMENT_NAME, DEPT.LOCATION
FROM EMPLOYEES EMP 
JOIN DEPARTMENTS DEPT
ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID;

#Find employees working in departments located in Delhi.
SELECT * FROM EMPLOYEES EMP
JOIN DEPARTMENTS DEPT
ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID
WHERE DEPT.location= 'DELHI';

#Display all departments and their employees using LEFT JOIN.
SELECT DEPT.DEPARTMENT_ID ,DEPT.DEPARTMENT_NAME, EMP.EMPLOYEE_ID, EMP.FIRST_NAME,EMP.LAST_NAME
FROM  DEPARTMENTS DEPT
LEFT JOIN EMPLOYEES EMP
ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID;

#Find departments that have no employees.
SELECT DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME
FROM DEPARTMENTS DEPT
LEFT JOIN EMPLOYEES EMP
ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID
WHERE EMP.EMPLOYEE_ID IS NULL;

#Display employees and departments using RIGHT JOIN.
SELECT * FROM EMPLOYEES EMP
RIGHT JOIN DEPARTMENTS DEPT
ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID;

#Display each employee with their manager using SELF JOIN.
SELECT EMP.EMPLOYEE_ID,EMP.FIRST_NAME,EMP.LAST_NAME,
MGR.EMPLOYEE_ID AS MANAGER_ID,MGR.FIRST_NAME AS MANAGER_FIRST_NAME,MGR.LAST_NAME AS MANAGER_LAST_NAME
FROM EMPLOYEES EMP
INNER JOIN EMPLOYEES MGR
  ON EMP.MANAGER_ID=MGR.EMPLOYEE_ID;
  
#Display employee salary and manager salary using SELF JOIN.
SELECT EMP.EMPLOYEE_ID, EMP.SALARY AS EMPPLOYEE_SALARY,
  MGR.EMPLOYEE_ID AS MANAGER_ID, MGR.SALARY AS MANAGER_SALARY
FROM EMPLOYEES EMP
INNER JOIN EMPLOYEES MGR
  ON EMP.MANAGER_ID=MGR.EMPLOYEE_ID;

#Find employees earning more than their manager.
SELECT EMP.EMPLOYEE_ID, EMP.SALARY AS EMPPLOYEE_SALARY,
  MGR.EMPLOYEE_ID AS MANAGER_ID, MGR.SALARY AS MANAGER_SALARY
FROM EMPLOYEES EMP
INNER JOIN EMPLOYEES MGR
  ON EMP.MANAGER_ID=MGR.EMPLOYEE_ID
WHERE EMP.SALARY>MGR.SALARY;

#Display products with their category names.
USE ECOMMERCE_DB;

SELECT PRODUCTS.PRODUCT_ID,PRODUCTS.PRODUCT_NAME,CATEGORIES.CATEGORY_NAME
FROM PRODUCTS
INNER JOIN CATEGORIES
ON PRODUCTS.CATEGORY_ID=CATEGORIES.CATEGORY_ID;

#Display customers and their orders.
SELECT CUSTOMERS.CUSTOMER_ID,CUSTOMERS.FIRST_NAME,CUSTOMERS.LAST_NAME,
ORDERS.ORDER_ID FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID=ORDERS.CUSTOMER_ID;

#Display each order with customer name and order status.
SELECT ORDERS.ORDER_ID, CUSTOMERS.FIRST_NAME,CUSTOMERS.LAST_NAME,ORDERS.STATUS
FROM ORDERS
LEFT JOIN CUSTOMERS
ON CUSTOMERS.CUSTOMER_ID=ORDERS.CUSTOMER_ID;

#Display each order item with product name, quantity, and unit price.
SELECT ORDER_ITEMS.ORDER_ID,ORDER_ITEMS.QUANTITY,ORDER_ITEMS.UNIT_PRICE, PRODUCTS.PRODUCT_NAME
FROM ORDER_ITEMS 
LEFT JOIN PRODUCTS 
ON ORDER_ITEMS.PRODUCT_ID=PRODUCTS.PRODUCT_ID;




